### PR TITLE
fix fleets on missions are not counted towards highscore

### LINKED ISSUE #793: [BUG] Ships on missions are removed from point/highscore calculation
**Describe the bug**
When ships are sent on a mission, the highscore points they yield will be exempt from the highscore calculation for as long as the ships are not stationed on a planet.

**To Reproduce**
1. Send ships on a mission.
2. Wait for the highscore calculation to happen.
3. Watch the points highscore points drop.

**Expected behavior**
Ships should be counted towards the point / highscore calculation, whether they are in motion or not.

### PR DESCRIPTION
**Pull request by rbardtke**
## Description
fix fleets on missions are not counted towards highscore

### Type of Change:
- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (please describe):

## Related Issues
Fixes #793 

## Checklist
Before submitting this pull request, ensure all following requirements as outlined in [CONTRIBUTING.md](https://github.com/lanedirt/OGameX/blob/main/CONTRIBUTING.md) are met:

- [ ] **Code Standards:** Code adheres to PSR-12 coding standards. Verified with Laravel Pint.
- [ ] **Static Analysis:** Code passes PHPStan static code analysis.
- [ ] **Testing:**
    - Relevant unit and feature tests are included or updated.
    - Tests successfully run locally.
- [ ] **CSS & JS Build:** CSS and JS assets are compiled using Laravel Mix if any changes are made to JS/CSS files.
- [ ] **Documentation:** Documentation has been updated to reflect any changes made.

## Additional Information
Add any additional context, screenshots, or explanations to help reviewers understand your PR. If this change introduces any breaking changes or significant impacts, please detail them here.

### CODE REVIEW

File: app/Services/HighscoreService.php [hunk 1]
```diff
@@ -49,6 +50,135 @@ public function setHighscoreType(int $type): void
...
+        foreach ($activeMissions as $mission) {
+            // Skip processed missions (already counted on planet)
+            if ($mission->processed) {
+                continue;
+            }
+
+            // Skip return missions - ships are already counted in the parent mission
+            if ($mission->parent_id !== null) {
+                continue;
+            }
```
Comment (lanedirt) [inline app/Services/HighscoreService.php]: I'm not sure if this will work. Because the `getActiveFleetMissionsSentByCurrentPlayer()` method should only return active missions that are not processed yet.

And so if a parent mission has been completed and a return mission is started, only the return mission will be returned by the method above. So I think we shouldn't skip the return missions here, but process them as usual.

Can you double check this?

File: app/Services/HighscoreService.php [hunk 2]
```diff
@@ -49,6 +50,135 @@ public function setHighscoreType(int $type): void
...
```
Comment (lanedirt) [inline app/Services/HighscoreService.php]: See the other comment

**Review by lanedirt — CHANGES_REQUESTED** [review]
Hi @rbardtke,

Thanks for looking into this! Overall the approach looks solid to me, but I do have a comment regarding the parent mission check: can you take a look at this?

File: app/Services/HighscoreService.php (hunk 2 above)
Comment (rbardtke) [reply app/Services/HighscoreService.php]: @lanedirt you are right this was wrong, i fixed and tested it on my local instance, works fine for me

**Comment by lanedirt** [comment]
Awesome, thanks for the fix. LGTM, merging!
