### PR TITLE
Fix #773: Display Interplanetary Missile range based on Impulse Drive level

### LINKED ISSUE #773: [BUG] Interplanetary Missiles don't show their range
**Describe the bug**
In the description in the defenses-view, Interplanetary Missiles currently do not show their range.

**To Reproduce**
See Screenshots

**Expected behavior**
The calculation for their range is already being done in the background (I am assuming). These values need to be printed in the description as well, informing the player of the missiles' range.

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by nguyenthanhan**
## Description
Fixes Interplanetary Missiles not displaying their range in the defense view. The `??` placeholder is now replaced with the actual range calculated from the player's Impulse Drive level using the formula: `max(0, impulse_drive_level * 5 - 1)`.

### Type of Change:
- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (please describe):

## Related Issues
Fixes #773

## Checklist
- [x] **Code Standards:** Code adheres to PSR-12 coding standards. Verified with Laravel Pint.
- [x] **Static Analysis:** Code passes PHPStan static code analysis.
- [x] **Testing:** Defense-related tests passed (7 tests, 139 assertions).
- [x] **CSS & JS Build:** No CSS/JS changes.
- [x] **Documentation:** No documentation changes needed.

## Additional Information
- Modified `app/Http/Traits/ObjectAjaxTrait.php` 
- Follows existing pattern used for Solar Satellite descriptions
- Example: Impulse Drive level 3 = 14 systems range

### CODE REVIEW

File: app/Http/Traits/ObjectAjaxTrait.php [hunk 1]
```diff
@@ -224,6 +224,15 @@ private function getObjectDescription($object, $planet): string
...
 
+        // Special handling for Interplanetary Missiles to show range based on impulse drive level
+        if ($object->machine_name === 'interplanetary_missile') {
+            $impulse_drive_level = $planet->getPlayer()->getResearchLevel('impulse_drive');
+            $missile_range = max(0, $impulse_drive_level * 5 - 1);
+
+            // Replace the ?? placeholder with the actual range
+            $description = str_replace('??', (string)$missile_range, $description);
+        }
+
```
Comment (lanedirt) [inline app/Http/Traits/ObjectAjaxTrait.php:235]: Instead of doing str_replace for the `??` part, instead we should do this similar to how it works for solar satellites, i.e. shorten the official description in the `GameObject` definition, and then here in the ObjectAjaxTrait.php append the "dynamic sentence".

Official OGame shows this in the object ajax trait short description (with dynamic sentence):

Image

But in other places like the technology tree, it shows the description only with the first sentence:

Image

Comment (anngth) [reply app/Http/Traits/ObjectAjaxTrait.php:235]: I fixed. Now follows the solar satellite pattern as suggested.

**Comment by lanedirt** [comment]
Looks good, thanks for the adjustments. Merging!
