### PR TITLE
Fleet dispatch allows deuterium consumption exceeding cargo capacity …

### LINKED ISSUE #760: [BUG] Fleet dispatch allows deuterium consumption exceeding cargo capacity
**Describe the bug**
The fleet dispatch system allows fleets to be sent on missions where the deuterium fuel consumption exceeds the total available cargo capacity of the ships. This validation error permits players to launch fleets that physically cannot carry enough fuel to complete their journey, as the required deuterium amount surpasses the maximum cargo space available. The system should reject such fleet configurations before dispatch, but currently allows them to be sent without warning or error.

**To Reproduce**
1. Select a fleet composition with limited cargo capacity (e.g., Destroyers for expedition missions)
2. Choose a destination with significant distance from origin (e.g., from galaxy 1:3:1 to 5:3:16)
3. Observe the deuterium consumption calculation exceeds the total cargo capacity of the selected ships
4. Attempt to dispatch the fleet despite the negative cargo space remaining
5. Notice the system allows the fleet to be sent without validation error or warning

**Expected behavior**
The fleet dispatch system should prevent sending the fleet when the deuterium consumption for the journey exceeds the available cargo capacity. The system should either display an error message indicating insufficient cargo space for the required fuel.

**Screenshots**
Image

Image

**Additional Context:**
This issue is reproducible with any ship type and distance combination where fuel consumption > total cargo capacity. Destroyers on long-range expeditions reliably trigger this bug due to their low cargo-to-consumption ratio.

### PR DESCRIPTION
**Pull request by yazilimmz**
…#760 fixed

## Description
Please include a summary of the changes made to OGameX and their purpose. Clearly describe what this PR does and why it is necessary.

### Type of Change:
- [x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (please describe):

## Related Issues
Fixes #760

## Checklist
Before submitting this pull request, ensure all following requirements as outlined in [CONTRIBUTING.md](https://github.com/lanedirt/OGameX/blob/main/CONTRIBUTING.md) are met:

- [x] **Code Standards:** Code adheres to PSR-12 coding standards. Verified with Laravel Pint.
- [x] **Static Analysis:** Code passes PHPStan static code analysis.
- [x] **Testing:**
    - Relevant unit and feature tests are included or updated.
    - Tests successfully run locally.
- [x] **CSS & JS Build:** CSS and JS assets are compiled using Laravel Mix if any changes are made to JS/CSS files.
- [x] **Documentation:** Documentation has been updated to reflect any changes made.

## Additional Information
Additionally, this change includes backend validation for fleet cargo capacity, which was not being checked before. This ensures that fleets cannot be dispatched if the cargo capacity is insufficient.

### CODE REVIEW

File: app/GameMissions/Abstracts/GameMission.php [hunk 1]
```diff
@@ -184,6 +184,19 @@ public function start(PlanetService $planet, Coordinate $targetCoordinate, Plane
...
+        // Check if the player has sufficient deuterium storage capacity for the fleet.
+        if ($totalCargoCapacity < $consumption) {
+            throw new Exception(__('You don\'t have sufficient storage capacity!'));
+        }
+
+        // Check if the fleet will exceed the fleet cargo capacity.
+        $total_resources = $resources->sum();
+        if ($total_resources > $totalCargoCapacity) {
+            throw new Exception('Resources exceed fleet cargo capacity.');
+        }
```
Comment (lanedirt) [inline app/GameMissions/Abstracts/GameMission.php:198]: Sanity check (I haven't tested this on the official game): don't we need to add the deuterium consumption to the $total_resources check on line 196, so we check if cargo capacity equals or exceeds total resources being sent + deuterium consumption?

As now if I read this correctly it looks like it e.g. a fleet has a cargo capacity of 100k resources, and the deuterium consumption for the trip is 50k... this check still allows to send along 100k of cargo, while this should be 50k, right?

Comment (yazilimmz) [reply app/GameMissions/Abstracts/GameMission.php:198]: It works exactly like this in the original OGame as well. You can test it yourself if you want. It seemed ridiculous to me too, but unfortunately, that's how it is. Maybe there is a bug there too :)

Comment (lanedirt) [reply app/GameMissions/Abstracts/GameMission.php:198]: Thanks for your reply! I just checked it, and indeed checks out that this is the way the official game does it too. So then it's perfect as-is, thanks for your attention to detail 😄 !

**Comment by lanedirt** [comment]
LGTM, merging!
