### PR TITLE
[Bug] cant build terraformer despite all conditions met #1143

### LINKED ISSUE #1143: [BUG] Cant build Terraformer despite all conditions met
**Describe the bug**
Currently impossible to build a terraformer with the regular "improve" button. Can only build it via the small green up arrow.

### PR DESCRIPTION
**Pull request by piciolo**
Ottima scelta, chiudiamo ufficialmente la pratica per il Terraformista! Questo era un bug particolarmente insidioso perché creava confusione tra i giocatori, facendo sembrare il gioco "rotto" quando invece era solo un errore di calcolo dell'energia.

Come da tua richiesta, ecco il form compilato sia in inglese (da incollare su GitHub) che in italiano per tua comodità.

🇬🇧 Da incollare su GitHub (English)
Description
This PR fixes a logic discrepancy between the building overlay and the quick upgrade tile regarding energy requirements for the Terraformer and Space Dock.

Previously, getObjectMaxBuildAmount() calculated the buildable amount based on free energy (energy()), which incorrectly blocked the "Improve" button if the planet's energy consumption (from mines) left a balance lower than the requirement. In OGame, energy for these specific buildings is a capacity requirement, not a consumable resource.

Changes:

Updated the energy check in the building validation logic to use energyProduction() (total production) instead of energy() (free energy).

This aligns the overlay button behavior with the quick upgrade arrow on the planet tile, which was already correctly using the production capacity.

Type of Change:
[x] Bug fix

[ ] Feature enhancement

[ ] Documentation update

[ ] Other (please describe):

Related Issues
Fixes #1143

Checklist
[x] Automated Refactoring: Rector has been run and no outstanding issues remain.

[x] Code Standards: Code adheres to PSR-12 coding standards. Verified with Laravel Pint.

[x] Static Analysis: Code passes PHPStan static code analysis.

[x] Testing:

Relevant unit and feature tests are included or updated.

Tests successfully run locally.

[x] CSS & JS Build: CSS and JS assets are compiled using Laravel Mix.

image

### CODE REVIEW

File: app/Services/ObjectService.php [hunk 1]
```diff
@@ -531,7 +531,7 @@ public static function getObjectMaxBuildAmount(string $machine_name, PlanetServi
         }
 
         if ($price->energy->get() > 0) {
-            $max_build_amount[] = floor($planet->energy()->get() / $price->energy->get());
+            $max_build_amount[] = floor($planet->energyProduction()->get() / $price->energy->get());
```
Comment (Geda173) [inline app/Services/ObjectService.php]: Unfortunately, it is not that easy. While the Terraformer and the Space Dock calculate with total energy production, Graviton Technology needs the 300k energy to be available at the time of research. This change makes it possible to research Graviton Technology with a total production of 300k energy, but less than that currently available.

File: app/Services/ObjectService.php [hunk 2]
```diff
@@ -514,6 +514,7 @@ public static function getObjectMaxBuildAmount(string $machine_name, PlanetServi
                 return 0;
             }
         }
+        $object = self::getObjectByMachineName($machine_name);
```
Comment (Geda173) [inline app/Services/ObjectService.php]: This object lookup is unnecessary. `$machine_name` is already in scope and can be used directly for the check below.

File: app/Services/ObjectService.php [hunk 3]
```diff
@@ -531,7 +532,13 @@ public static function getObjectMaxBuildAmount(string $machine_name, PlanetServi
...
 
         if ($price->energy->get() > 0) {
-            $max_build_amount[] = floor($planet->energy()->get() / $price->energy->get());
+            // Terraformer (33) and Space Dock (36) only require total energy production to be
+            // at the required level, regardless of how much is currently consumed by mines.
+            // All other objects (e.g. Graviton Technology 199) require free/net energy surplus.
+            $energyAvailable = in_array($object->id, [33, 36])
+                ? $planet->energyProduction()->get()
+                : $planet->energy()->get();
+            $max_build_amount[] = floor($energyAvailable / $price->energy->get());
```
Comment (Geda173) [inline app/Services/ObjectService.php:539]: The rest of this function uses machine name strings for special-case checks (e.g. `'small_shield_dome'`, `'interplanetary_missile'`). Since `$machine_name` is already in scope, this could be simplified to:
                                                                                                                                                                                                               
  ```php                                                                                                                                                                                                       
  $energyAvailable = in_array($machine_name, ['terraformer', 'space_dock'])                                                                                                                                    
      ? $planet->energyProduction()->get()                                                                                                                                                                     
      : $planet->energy()->get();
  ``` 
This removes the need for the `getObjectByMachineName() `call above and is consistent with the pattern used elsewhere in this function.

**Review by Geda173 — CHANGES_REQUESTED** [review]
I have added some comments below.

File: app/Services/ObjectService.php (hunk 2 above)
Comment (Geda173) [reply app/Services/ObjectService.php]: This line still needs to be deleted as it is dead code.

**Review by Geda173 — CHANGES_REQUESTED** [review]

**Review by Geda173 — CHANGES_REQUESTED** [review]
The fix is still incorrect. I can research Graviton Technology despite not having 300k energy freely available. It is still accounting for the total energy available, not the currently available energy.

Image

**Review by Geda173 — APPROVED** [review]

**Review by lanedirt — APPROVED** [review]
