### PR TITLE
Implement moon jump gate functionality #479 fix

### LINKED ISSUE #479: Implement moon jump gate functionality

### PR DESCRIPTION
**Pull request by yazilimmz**
## Description
Please include a summary of the changes made to OGameX and their purpose. Clearly describe what this PR does and why it is necessary.

### Type of Change:
- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (please describe):

## Related Issues
Fixes #479

## Checklist
Before submitting this pull request, ensure all following requirements as outlined in [CONTRIBUTING.md](https://github.com/lanedirt/OGameX/blob/main/CONTRIBUTING.md) are met:

- [x] **Code Standards:** Code adheres to PSR-12 coding standards. Verified with Laravel Pint.
- [x] **Static Analysis:** Code passes PHPStan static code analysis.
- [x] **Testing:**
    - Relevant unit and feature tests are included or updated.
    - Tests successfully run locally.
- [ ] **CSS & JS Build:** CSS and JS assets are compiled using Laravel Mix if any changes are made to JS/CSS files.
- [ ] **Documentation:** Documentation has been updated to reflect any changes made.

## Additional Information

I've completed the backend implementation for the Jump Gate feature. I've implemented comprehensive validations and edge case handling to prevent potential bugs. Please review thoroughly and let me know if there are any additional security measures or checks that should be added.
Jump Gate Cooldown Formula:

Since this formula isn't officially documented in OGame, I reverse-engineered it through my own in-game testing and forum research:
```
Cooldown (minutes) = X * (1 - JumpGate Level * 0.10)
X = 60 / Fleet War Speed
```

### CODE REVIEW

**Comment by Geda173** [comment]
Hi @yazilimmz,

I haven't checked the work itself, I am only commenting about the formula for the cooldown of the Jump Gate. The German OGame Wiki ties the cooldown to the universe speed and not the Fleet War Speed. Tying it to War Speed hampers the functinoality of the gate as it is not just meant to quickly move beligerent fleets.

The settings for OGameX in its current version do not allow for "simple" universe speed settings so it needs to be tied to *something*. Historically, speed universes in OGame had one multiplier for *everything*. While I think that tying it to Fleet War Speed is a valid approach, I would propose to tie it to either Econ Speed or implement a Jump Gate Cooldown Multiplier in the server settings to completely detach it from fleet speeds, as they are too granular to strike a "fair" balance.

**Comment by yazilimmz** [comment]
> Hi @yazilimmz,
> 
> I haven't checked the work itself, I am only commenting about the formula for the cooldown of the Jump Gate. The German OGame Wiki ties the cooldown to the universe speed and not the Fleet War Speed. Tying it to War Speed hampers the functinoality of the gate as it is not just meant to quickly move beligerent fleets.
> 
> The settings for OGameX in its current version do not allow for "simple" universe speed settings so it needs to be tied to _something_. Historically, speed universes in OGame had one multiplier for _everything_. While I think that tying it to Fleet War Speed is a valid approach, I would propose to tie it to either Econ Speed or implement a Jump Gate Cooldown Multiplier in the server settings to completely detach it from fleet speeds, as they are too granular to strike a "fair" balance.

I occasionally play official OGame. Based on my experience there, I know that the Jump Gate cooldown is actually tied to Fleet War Speed, not Economy Speed.

File: app/Services/PlanetService.php [hunk 1]
```diff
@@ -126,6 +126,16 @@ public function getPlayer(): PlayerService|null
...
+    /**
+     * Get the planet model.
+     *
+     * @return Planet
+     */
+    public function getPlanet(): Planet
+    {
+        return $this->planet;
+    }
+
```
Comment (lanedirt) [inline app/Services/PlanetService.php:172]: Instead of exposing the raw planet Eloquent db object, could you please add separate getter methods instead for the new jumpgate properties that need to be accessed?

E.g. applies to this (and possibly others):

```php
$cooldown_until = $moon->getPlanet()->jump_gate_cooldown;
```

**Comment by lanedirt** [comment]
I just tested it, looks to be working great! Thanks for the adjustments. Merging!
