### PR TITLE
implement fleet movement page #419 fix

### LINKED ISSUE #419: Implement "fleet movement" page
The fleet movement page is not implemented yet. It currently shows static placeholders. The active fleets will need to be shown here.

You can navigate to this page by clicking on the triangles icon next to the "Fleet" menu item.

Screenshot 2024-10-25 at 15 43 34

## Context
Tip: OGameX already contains logic to show active fleets. The existing logic covers the "No fleet movement" area next to the message and chat icons near the top of the page. This existing logic can most likely be reused for the fleet movement page. See this file for more information:

```
app/Http/Controllers/FleetEventsController.php
```

### PR DESCRIPTION
**Pull request by yazilimmz**
## Description
Monitor all their active fleet missions
See countdown timers until arrival/return
View fleet composition and cargo details
Recall fleets if needed

### Type of Change:
- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (please describe):

## Related Issues
Fixes #419 

## Checklist
Before submitting this pull request, ensure all following requirements as outlined in [CONTRIBUTING.md](https://github.com/lanedirt/OGameX/blob/main/CONTRIBUTING.md) are met:

- [x] **Code Standards:** Code adheres to PSR-12 coding standards. Verified with Laravel Pint.
- [x] **Static Analysis:** Code passes PHPStan static code analysis.
- [x] **Testing:**
    - Relevant unit and feature tests are included or updated.
    - Tests successfully run locally.
- [ ] **CSS & JS Build:** CSS and JS assets are compiled using Laravel Mix if any changes are made to JS/CSS files.
- [ ] **Documentation:** Documentation has been updated to reflect any changes made.

## Additional Information
Add any additional context, screenshots, or explanations to help reviewers understand your PR. If this change introduces any breaking changes or significant impacts, please detail them here.

### CODE REVIEW

File: app/GameMissions/Abstracts/GameMission.php [hunk 1]
```diff
@@ -44,6 +44,11 @@ abstract class GameMission
      */
     protected static FleetSpeedType $fleetSpeedType;
 
+    /**
+     * @var string The friendly status for UI styling ('friendly', 'neutral', or 'hostile').
+     */
+    protected static string $friendlyStatus;
```
Comment (lanedirt) [inline app/GameMissions/Abstracts/GameMission.php]: Could you refactor this to be an enum instead of a raw string, similar to `FleetSpeedType`. Then we will have type safety enforcement, ensuring all GameMission implementations  use either 'friendly', 'neutral', or 'hostile'.

**Comment by lanedirt** [comment]
Just tested it and works and looks very nice, awesome!  Thanks for the work on this @yazilimmz! Merging!
