### PR TITLE
Fix adjust missile attack behavior when there are 0 missiles available #1054

### LINKED ISSUE #1054: [BUG]  Adjust missile attack behavior when there are 0 missiles available
**Describe the bug**
OGameX currently features an error screen when wanting to send a missile attack to a planet with the currently selected planet not having any missiles.

**Expected behavior**
The missile attack button should be available and open up the missile attack dialog, but display 0 rockets and have the launch button be greyed out.

### PR DESCRIPTION
**Pull request by piciolo**
Description
This PR improves the UX and prevents errors when a player has no Interplanetary Missiles available on their active planet. Following community feedback, the fix now operates on two levels:

Galaxy View: The missile attack icon is now hidden from the planet's mouse-over menu if the player's active planet has 0 missiles.

Overlay Fallback: As a safeguard for players who haven't refreshed their page after firing all missiles, the "Fire" button in the missile attack overlay is now visually and functionally disabled if the missile count is 0.

Type of Change:
[x] Bug fix

[ ] Feature enhancement

[ ] Documentation update

[ ] Other (please describe):

Related Issues
Fixes #1054

Checklist
[x] Automated Refactoring: Rector has been run and no outstanding issues remain.

[x] Code Standards: Code adheres to PSR-12 coding standards. Verified with Laravel Pint.

[x] Static Analysis: Code passes PHPStan static code analysis.

[x] Testing:

Verified that the missile icon disappears from the Galaxy view when the ammo count is 0.

Verified that the "Fire" button is disabled in the overlay if accessed directly with 0 missiles.

Tests successfully run locally.

[x] CSS & JS Build: N/A.

[x] Documentation: UI behavior now matches the expected game flow described in the issue feedback.

Additional Information
This dual approach ensures a clean UI by not showing impossible actions, while also preventing LogicException errors in edge cases where the overlay is already open or accessed via a stale page state.
image

image

### CODE REVIEW

**Comment by piciolo** [comment]
@Geda173 
Let me know if that's okay now, thank you.

**Comment by Geda173** [comment]
> @Geda173 Let me know if that's okay now, thank you.

Hi @piciolo,

I just checked again in OGame and the flow is a bit different there. I have attached a video. Disregard all the colored options, those are part of an extension and not part of the original game. The main difference here is that after depelting all Interplanetary Missiles and then opening the missile dialogue again, the button is not greyed out. Instead the dialogue remains fully functional. Upon firing with 0 missiles, the window closes and an error fadebox displays an error about insuffiecient range.

https://github.com/user-attachments/assets/565d48d1-c93c-472e-89ea-7f1d1597c2bc

**Comment by piciolo** [comment]
@Geda173 
Thank you for the video and the feedback! I have updated the PR to match the exact flow shown:

UI Changes: >   - The missile attack modal now opens even if the player has 0 missiles (range check is now performed only on the system distance).

The "Fire" button is never disabled, even with zero missiles.

The input field defaults to 0 when no missiles are available.

Backend & Logic:

Updated GalaxyController.php to allow the modal to open with 0 missiles and refined the validation logic.

If an attack is launched with 0 missiles, the backend returns a 400 error with the specific message: "Insufficient range (research level impulse drive) of your interplanetary missiles!".

Added the insufficient_range translation key to English, Italian, and Dutch.

JavaScript Flow: >   - The modal now closes automatically before displaying the red error fadebox when a "close_overlay" flag is received from the server (matching the video behavior).

This should now be 100% faithful to the original game. Could you please check this in the preview deployment? Thanks!

image

**Comment by Geda173** [comment]
Hi @piciolo,

I just tested the implementation and we have a regression now. When there are 0 missiles available or the planet is out of range, the missile attack option in /galaxy should not be visible in the mouse over of a target planet. The only instance in which the button should be visible while at 0 missiles is when you just fired all of your missiles and there hasn't been a page refresh yet.

**Comment by piciolo** [comment]
@Geda173 
I've just pushed a fix for the regression you pointed out in.

The issue was a discrepancy between the backend flags and the frontend rendering logic in the Galaxy view. I've now added an explicit check for availableMissiles directly in the JS rendering function.

Locally, the "Missile Attack" link is now correctly hidden when missiles are at 0 or targets are out of range. Could you please re-test the latest PR preview whenever you have a moment?

Thanks!

**Review by Geda173 — APPROVED** [review]
Frontend changes are looking good, the flow is currently the way it should be. I'll let @lanedirt take another look and then it should be good to merge.

File: app/Http/Controllers/GalaxyController.php [hunk 1]
```diff
@@ -109,7 +109,7 @@ public function getGalaxyArray(int $galaxy, int $system, PlayerService $player,
 
         $planets = [];
         foreach ($planet_list as $planet) {
-            $planetService = $planetServiceFactory->makeFromModel($planet);
+            $planetService = $planetServiceFactory->makeFromModel($planet instanceof Planet ? $planet : new Planet((array)$planet));
```
Comment (lanedirt) [inline app/Http/Controllers/GalaxyController.php]: Is this newly added sanity check actually necessary here? 

I have personally not seen errors regarding the way the `makeFromModel()` works previously.

**Review by lanedirt — COMMENTED** [review]
Hi both, thanks for the work and review on this! A small comment from my side. But not blocking for the merge. Other than this looks good!

File: app/Http/Controllers/GalaxyController.php (hunk 1 above)
Comment (piciolo) [reply app/Http/Controllers/GalaxyController.php]: You're right, this check isn't necessary and I'm removing it.

I added it in commit aa3235d ("Allow missile overlay with zero missiles") as a defensive precaution, but it was tangential to that commit's actual purpose and not fixing any observed bug. In this context $planet_list comes from Planet::where(...)->get(), so Eloquent guarantees each $planet is a Planet instance; the else branch (new Planet((array)$planet)) is unreachable. On top of that, makeFromModel() is type-hinted as Planet $planet, so any non-Planet input would already fail at the signature. If the fallback ever did trigger it would silently pass a non-persisted model to PlanetService, which would be worse than a clean TypeError. Reverted to the original line.
