### PR TITLE
feat(expeditions): adjust ship-finding hierarchy and fix outcome weights

### LINKED ISSUE #762: Adjust expedition ship discovery logic to allow finding higher-tier ships
**Description**
Expeditions never yield ships that are higher in the hierarchy than those sent. Reviewing `ExpeditionMission.php`, I found this comment:

> // Define expedition hierarchy levels - each level can find ships at that level and all lower levels.

In the official game, expeditions can find ships one tier higher than those included in the fleet. The change tying expedition outcomes to the rank 1 player was introduced in version 5.7.5 (2014), which predates this project’s cutoff date. While I haven't been able to fully determine whether that was also the time in which "higher findings" were introduced, I would like to propose this change regardless.

**Proposed fix**
Adjust the ship-finding logic so expeditions can yield ships up to one tier higher than the highest ship sent.

### PR DESCRIPTION
**Pull request by Geda173**
This update refines expedition behavior and corrects a minor weighting error.

Changes include:
- Expedition ship discovery logic can now yield ships up to **one tier higher** than the highest ship sent, capped at the top defined tier.
- Added the **Death Star** to the expedition hierarchy (level 9) so sending it properly influences the findable tier ceiling, while still excluding it from being found.
- Explicitly **excluded non-findable ships** (`deathstar`, `colony_ship`, `recycler`, `solar_satellite`) from reward generation.
- Clarified hierarchy comments and maintained existing cargo and max-resource constraints.
- Fixed the **outcomeWeights** total (was 1005 → now 1000) by adjusting the "nothing" entry from 270 to 265. (We can subtract the 5 additional points from anywhere, really. I chose "nothing" because merchant and Dark Matter are not functional yet, giving "nothing" a disproportional amount of weight.)

Result:
- Sending a Death Star no longer defaults to low-tier/no rewards.
- Highest obtainable expedition find remains capped at Destroyer.
- Expedition outcomes now correctly sum to 100% probability.

## Description
Please include a summary of the changes made to OGameX and their purpose. Clearly describe what this PR does and why it is necessary.

### Type of Change:
- [X] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (please describe):

## Related Issues
Fixes #762 

## Checklist
Before submitting this pull request, ensure all following requirements as outlined in [CONTRIBUTING.md](https://github.com/lanedirt/OGameX/blob/main/CONTRIBUTING.md) are met:

- [ ] **Code Standards:** Code adheres to PSR-12 coding standards. Verified with Laravel Pint.
- [ ] **Static Analysis:** Code passes PHPStan static code analysis.
- [ ] **Testing:**
    - Relevant unit and feature tests are included or updated.
    - Tests successfully run locally.
- [ ] **CSS & JS Build:** CSS and JS assets are compiled using Laravel Mix if any changes are made to JS/CSS files.
- [ ] **Documentation:** Documentation has been updated to reflect any changes made.

Additional information:

After testing on a local branch, the outcome distribution behaves as expected:

> Failed ~30%, Delay ~7%, Speedup ~2%, GainResources ~35%, GainShips ~25%, LossOfFleet ~0.3%

Live tests with users are still ongoing.

### CODE REVIEW

File: app/GameMissions/ExpeditionMission.php [hunk 1]
```diff
@@ -348,12 +350,24 @@ private function processExpeditionGainShipsOutcome(FleetMission $mission): UnitC
...
             $possibleShipMachineNames = array_merge($possibleShipMachineNames, $expeditionLevels[$level]);
         }
 
+        // Exclude ships that should never be found (even if they affect hierarchy)
+        // IMPORTANT: These ships can affect the hierarchy ceiling but MUST never be found as expedition rewards.
+        $nonFindableShips = ['deathstar', 'colony_ship', 'recycler', 'solar_satellite'];
+        $possibleShipMachineNames = array_values(array_filter(
+            $possibleShipMachineNames,
+            fn ($mn) => !in_array($mn, $nonFindableShips, true)
+        ));
```
Comment (lanedirt) [inline app/GameMissions/ExpeditionMission.php]: This filtering can be simplified by using the built-in `array_diff()` method:
```php
$possibleShipMachineNames = array_diff($possibleShipMachineNames, $nonFindableShips);

```

Comment (Geda173) [reply app/GameMissions/ExpeditionMission.php]: Awesome, thanks for the suggestion. I have made the change.

**Comment by lanedirt** [comment]
Looks good, thanks a lot for your contribution!

**Comment by Kays** [comment]
@Geda173 I haven't tested this change yet, so I'm just going off the change listing on GitHub. Please correct me if I'm wrong in my assessment.

As far as I know, Deathstar, Colony Ship, and Recycler do not yield any ships. If you send an Expedition with only one Deathstar, Colony Ship, and/or Recycler and nothing else, that cannot yield any ships. So including Deathstar in the hierarchy listing would effectively set the max level to 8 if the player sends a Deathstar, even though the logic prevents the player from gaining Deathstars as ship rewards from the Expedition. Perhaps what you implemented is how it used to work; I cannot confirm because there's no official OGame version available that OGameX is based on. In the current code, Colony Ship and Recycler are in the excluded list but are not listed in the levels array so they are not counted, unlike Deathstar. I don't know why Solar Satellites are listed as exclusions when they cannot be sent.

Having said all that, I think the current level structure may be incorrect. Again, I cannot test on any official OGame version that OGameX is based on, so I can only reference what I know based on the current game's state. For example, from my testing in Bermuda, sending a Small Cargo cannot yield a Large Cargo. Same for sending an Espionage Probe - that cannot yield a Large Cargo either. So I think a more accurate structure isn't to use levels, but a flat array, and the logic remains that the result can include the next entry's ship. For example:
```php
$ship_tiers = [
    'espionage_probe',
    'small_cargo',
    'light_fighter',
    'large_cargo',
    'heavy_fighter',
    ...
];
```
Sending a Small Cargo can yield Espionage Probe, Small Cargo, and Light Fighter. Sending a Light Fighter can yield Espionage Probe, Small Cargo, Light Fighter, and Large Cargo. Et cetera.

**Comment by Geda173** [comment]
> @Geda173 I haven't tested this change yet, so I'm just going off the change listing on GitHub. Please correct me if I'm wrong in my assessment.
> 
> As far as I know, Deathstar, Colony Ship, and Recycler do not yield any ships. If you send an Expedition with only one Deathstar, Colony Ship, and/or Recycler and nothing else, that cannot yield any ships. So including Deathstar in the hierarchy listing would effectively set the max level to 8 if the player sends a Deathstar, even though the logic prevents the player from gaining Deathstars as ship rewards from the Expedition. Perhaps what you implemented is how it used to work; I cannot confirm because there's no official OGame version available that OGameX is based on. In the current code, Colony Ship and Recycler are in the excluded list but are not listed in the levels array so they are not counted, unlike Deathstar. I don't know why Solar Satellites are listed as exclusions when they cannot be sent.
> 
> Having said all that, I think the current level structure may be incorrect. Again, I cannot test on any official OGame version that OGameX is based on, so I can only reference what I know based on the current game's state. For example, from my testing in Bermuda, sending a Small Cargo cannot yield a Large Cargo. Same for sending an Espionage Probe - that cannot yield a Large Cargo either. So I think a more accurate structure isn't to use levels, but a flat array, and the logic remains that the result can include the next entry's ship. For example:
> 
> ```
> $ship_tiers = [
>     'espionage_probe',
>     'small_cargo',
>     'light_fighter',
>     'large_cargo',
>     'heavy_fighter',
>     ...
> ];
> ```
> 
> Sending a Small Cargo can yield Espionage Probe, Small Cargo, and Light Fighter. Sending a Light Fighter can yield Espionage Probe, Small Cargo, Light Fighter, and Large Cargo. Et cetera.

Hey there! I included the solar satellites because they _technically_ are a ship as they are produced in the shipyard. Of course they are stationary objects and nothing more than a glorified building. You can easily delete them from the code, it won't do anything, really.

I just looked at one of the many expedition calculators and it appears that sending a Death Star can yield, at max, a Heavy Fighter. So they apparently do yield _something_. We could switch the Death Star into the exclusion list or change the list of findable ships for the Death Star. It probably comes down to preference. I have never sent a Death Star on an expedition, because it's just not feasible at all. There are only downsides to it. But it does need to be taken into consideration.

**Comment by Kays** [comment]
> I just looked at one of the many expedition calculators and it appears that sending a Death Star can yield, at max, a Heavy Fighter. So they apparently do yield _something_. We could switch the Death Star into the exclusion list or change the list of findable ships for the Death Star. It probably comes down to preference. I have never sent a Death Star on an expedition, because it's just not feasible at all. There are only downsides to it. But it does need to be taken into consideration.

Mind linking me to one of those expedition calculators?

**Comment by Geda173** [comment]
> > I just looked at one of the many expedition calculators and it appears that sending a Death Star can yield, at max, a Heavy Fighter. So they apparently do yield _something_. We could switch the Death Star into the exclusion list or change the list of findable ships for the Death Star. It probably comes down to preference. I have never sent a Death Star on an expedition, because it's just not feasible at all. There are only downsides to it. But it does need to be taken into consideration.
> 
> Mind linking me to one of those expedition calculators?

Absolutely! I have been fiddling around with this one: https://logserver.net/expocalc/

**Comment by Kays** [comment]
> Absolutely! I have been fiddling around with this one: https://logserver.net/expocalc/

What am I doing wrong? I have 1 Deathstar and nothing else and it doesn't show any ship rewards. Even if I added a bunch of Deathstar, still nothing. Same if I include Colony Ship and/or Recycler. If you add any other ships like Large Cargo, alongside Deathstar, then it should report the corresponding findings, but that's due to the Large Cargo and not Deathstar.

**Comment by Geda173** [comment]
> > Absolutely! I have been fiddling around with this one: https://logserver.net/expocalc/
> 
> What am I doing wrong? I have 1 Deathstar and nothing else and it doesn't show any ship rewards. Even if I added a bunch of Deathstar, still nothing. Same if I include Colony Ship and/or Recycler. If you add any other ships like Large Cargo, alongside Deathstar, then it should report the corresponding findings, but that's due to the Large Cargo and not Deathstar.
> 
> 

You are not doing anything wrong, the mistake is mine. I had a LC erroneously still in there. That resulted in HF being on the findable list. So you are right, Death Stars need to be on the exclusion list. Good eye!
