### PR TITLE
Fixes #418 - Shop static layout bug

### LINKED ISSUE #418: [BUG] Fix recruit officers and shop static layout
**Describe the bug**
The lay-out of the following pages in the menu is broken:

- [x] Recruit Officers (Fixed by #420)
- [ ] Shop

Probably some CSS classes and/or static files such as images are missing.

**To Reproduce**
1. Click on one of the menu buttons as described above.
2. The lay-out will appear broken.

**Expected behavior**
The lay-out of the pages to be equal to how the official game works.

**Screenshots**
## This is the broken lay-out example:
Screenshot 2024-10-25 at 15 34 19
Screenshot 2024-10-25 at 15 34 14

## This is what it should look like according to the official game:
Screenshot 2024-10-25 at 15 39 56
Screenshot 2024-10-25 at 15 40 01

**Additional context**
This issue is only meant to cover the lay-out. The actual implementation of the Recruit Officers and Shop functionality can be done later. The OGameX project does not and will not include any commercial features/payment options. So it is still up for discussion if and how we want to implement these features in a non-commercial way.

### PR DESCRIPTION
**Pull request by theshado40**
## Description

This fixes the layout for the shop page.  The alignment was completely off due to missing the shop body ID.  Also added a new test case for the shop page itself

### Type of Change:
- [x] Bug fix

## Related Issues

Fixes #[418]

## Checklist

Before submitting this pull request, ensure all following requirements as outlined in [CONTRIBUTING.md](https://github.com/lanedirt/OGameX/blob/main/CONTRIBUTING.md) are met:

- [x] **Code Standards:** Code adheres to PSR-12 coding standards. Verified with Laravel Pint.
- [x] **Static Analysis:** Code passes PHPStan static code analysis.
- [x] **Testing:**
    - Relevant unit and feature tests are included or updated.
    - Tests successfully run locally.

### CODE REVIEW

File: tests/Feature/ShopPageTest.php
Comment (lanedirt) [inline tests/Feature/ShopPageTest.php:1]: HTTP 200 checks already exist for most pages including the `/shop` page, see the test file `tests/Feature/Http200Test.php`.

So this means this test is a duplicate. Can you remove this file?

File: app/Http/Controllers/ShopController.php [hunk 1]
```diff
@@ -13,6 +13,9 @@ class ShopController extends OGameController
      */
     public function index(): View
     {
+        //Bug Fix #418, Ryan Sandnes, 2021-08-02
```
Comment (lanedirt) [inline app/Http/Controllers/ShopController.php]: The page works fine with this change, thanks! However this specific comment does not add much value as the Git commit history will already track why this line was added and author details. Can you remove this line comment?

**Review by lanedirt — CHANGES_REQUESTED** [review]
Thanks for taking the time to investigate and fix the lay-out issue! I have added two comments to the review, see above. Can you take a look at this?

File: tests/Feature/ShopPageTest.php
Comment (theshado40) [reply tests/Feature/ShopPageTest.php:1]: File has been removed!  I was thinking it tested for the specific issue at hand (not having the store ID set) as opposed to the page loading.

File: app/Http/Controllers/ShopController.php (hunk 1 above)
Comment (theshado40) [reply app/Http/Controllers/ShopController.php]: lol, not sure what I was even thinking on that one with a signature.  Not even the correct date=).  Removed!

**Comment by lanedirt** [comment]
Thanks for the fixes! Merging 😀
